name: Test Edge Paths

on:
    push:
    schedule:
        - cron: "00 12 * * *"

jobs:
    build-ununtu:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - ubuntu-18.04
                node_version:
                    - 14
                    - 16
                    - 17
                architecture:
                    - x64
        name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}
                  architecture: ${{ matrix.architecture }}
            - run: npm install
            - run: node tests/downloadEdge.js
            - run: for f in *.deb;do echo $f;sudo apt install -y  ./$f; done
            - run: ls
            - run: node tests/index.js

    build-window:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - windows-latest
                    - windows-2022
                node_version:
                    - 14
                    - 16
                    - 17
        name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}
                  architecture: ${{ matrix.architecture }}
            - uses: browser-actions/setup-edge@latest
              with:
                  edge-version: stable
            - uses: browser-actions/setup-edge@latest
              with:
                  edge-version: beta
            - uses: browser-actions/setup-edge@latest
              with:
                  edge-version: canary
            - uses: browser-actions/setup-edge@latest
              with:
                  edge-version: dev
            - run: npm install
            - run: node tests/index.js
